name: release_draft
on:
  push:
    tags:
      - 'v*'

jobs:
  release_draft:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          # Current Java LTS
          21,
        ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'   # When using Java 8, set 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: create release
        # Only upload artifacts built from latest java on one OS
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }}
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
